---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 6fec9b7edb08fd9989088709d864a7826dc74e80  # v0.15.12
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: ./.venv/bin/pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
