---
name: CI

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install pixi
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: latest
      - name: Run Format and Lint Checks
        run: |
          pixi run ruff check .
          pixi run ruff format --check .
      - name: Run tests
        run: pixi run test
